# Generated by Django 5.2 on 2025-04-08 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bm_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorOrActress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Actor (Actress) Name",
                "verbose_name_plural": "Actors (Actresses) Names",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Director Name",
                "verbose_name_plural": "Directors Names",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "average_rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ]
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="movies", to="bm_api.actororactress"
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="bm_api.director",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DirectorName",
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_rating__gte", 0.0), ("average_rating__lte", 5.0)
                ),
                name="average_rating_between_0_00_and_5_00",
            ),
        ),
    ]
