# Generated by Django 5.2 on 2025-04-08 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bm_api", "0002_actororactress_director_movie_delete_directorname_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="movie",
            name="average_rating_between_0_00_and_5_00",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="average_rating",
        ),
        migrations.AddField(
            model_name="movie",
            name="average_stars",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_stars__gte", 1), ("average_stars__lte", 5)
                ),
                name="average_rating_between_1_and_5",
            ),
        ),
    ]
